import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        StringBuffer bf=new StringBuffer("============= 订餐明细 =============\n");
        ArrayList<String>  discountItem=new ArrayList<>();
        double noSale=0d,saleMoney=0d;
        DecimalFormat format=new DecimalFormat("#.##");
        for(int i=0;i<inputs.size();i++){
            String[] inputArray=inputs.get(i).split(" x ");
            Iterator<Item> it=itemRepository.findAll().iterator();
            while (it.hasNext()){
                Item item=it.next();
                if(item.getId().equals(inputArray[0])){
                    bf.append(item.getName()+" x "+inputArray[1]+" = "+format.format(item.getPrice()*Integer.parseInt(inputArray[1]))+"元\n");

                    noSale+=item.getPrice()*Integer.parseInt(inputArray[1]);
                    if(salesPromotionRepository.findAll().get(1).getRelatedItems().contains(item.getId())){
                        saleMoney+=item.getPrice()/2*Integer.parseInt(inputArray[1]);
                        discountItem.add(item.getName());
                    }
                }
            }

        }
        bf.append("-----------------------------------\n");
        if(noSale>=30d&&saleMoney<=6d){
            bf.append(  "使用优惠:\n" +
                    "满30减6元，省6元\n" +
                    "-----------------------------------\n" );
            noSale-=6;
        }
        else if((noSale>=30d&&saleMoney>6d)||(noSale<30d&&saleMoney!=0d)){
            String discountMeal="";
            if(discountItem.size()>0) {
                if (discountItem.size() == 1) discountMeal = discountItem.get(0);
                else discountMeal = discountItem.get(0) + "，" + discountItem.get(1);
            }
            bf.append( "使用优惠:\n" +
                    "指定菜品半价("+discountMeal+")，省"+format.format(saleMoney)+"元\n" +
                    "-----------------------------------\n");
            noSale-=saleMoney;
        }
        bf.append("总计："+format.format(noSale)+"元\n" +
                "===================================");
        return bf.toString();
    }
}
